#!/usr/bin/python3
"""module to find factors of numbers"""

from sys import argv as arg
import math


def factors():
    """find factors of numbers in a file"""

    with open(arg[1]) as file:
        for line in file:
            number = int(line)

            print("{:d}=".format(number), end="")

            if number % 2 == 0:
                print("{}*2".format(number // 2))
                continue

            odd = int(math.sqrt(number))
            if odd % 2 == 0:
                odd += 1

            for x in range(3, odd + 1, 2):
                if number % x == 0:
                    print("{}*{}".format(x, number // x))
                    break
            if number % x != 0:
                print("{}={}*1".format(number, number))


factors()
